version: '2.4'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  db-migrations:
    build:
      context: back
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./back:/home/node/app
      - back-node_modules:/home/node/app/node_modules
    command: npx prisma migrate dev --preview-feature
    depends_on:
      db:
        condition: service_healthy

  s3:
    image: 'gliffy/fake-s3'
    ports:
      - 4569:4569
    healthcheck:
      test: wget http://localhost:4569/registry-c3pm-io --method=PUT
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PORT: 4000
      ALLOWED_ORIGIN: http://localhost:3000
      SESSION_SECRET: toto
      FRONTEND_URL: http://localhost:3000
      REGISTRY_BUCKET_NAME: registry-c3pm-io
      REGISTRY_SECRET: secret
      REGISTRY_KEY: key
      REGISTRY_URL: http://s3:4569
    volumes:
      - ./back:/home/node/app
      - back-node_modules:/home/node/app/node_modules
    depends_on:
      s3:
        condition: service_healthy
      db:
        condition: service_healthy
      db-migrations:
        condition: service_started

volumes:
  back-node_modules:
