parserOptions:
  ecmaVersion: 6
env:
  cypress/globals: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - cypress
rules:
  no-console:
    - error
    - allow:
        - warn
        - error
