parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  project: tsconfig.eslint.json
env:
  browser: true
extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
plugins:
  - testing-library
  - jest-dom
settings:
  import/resolver:
    alias:
        map:
        - ["components", "./components"]
        - ["utils", "./utils"]
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".json"]
overrides: [
  {
    files: ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)"],
    extends: ["plugin:testing-library/react"]
  },
]
rules:
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  import/no-extraneous-dependencies: [error, {devDependencies: ["**/*.stories.ts", "**/*.stories.tsx", "**/test/**.ts", "**/test/**.tsx"]}]
  import/order: [
    error,
    {
      groups: [
        "builtin",
        "external",
        "internal",
        "parent",
        "sibling",
        "index"
      ],
      newlines-between: "always"
    }
  ]
  testing-library/await-async-query: error
  testing-library/no-await-sync-query: error
  testing-library/no-debug: warn
  testing-library/no-dom-import: off
  jest-dom/prefer-checked: error
  jest-dom/prefer-enabled-disabled: error
  jest-dom/prefer-required: error
  jest-dom/prefer-to-have-attribute: error