name: Backend CI

on:
  pull_request:
    paths:
      - 'back/**'
      - .github/workflows/back.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      working-directory: ./back
      run: |
        npm ci
        npm run build
      env:
        CI: true

  test:

    runs-on: ubuntu-latest

    services:
      posgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      s3:
        image: 'localstack/localstack'
        ports:
        - 4566:4566
        env:
          REGISTRY_BUCKET_NAME: registry-c3pm-io
          SERVICES: s3
        options: >-
          --health-cmd "awslocal s3 ls"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: setup s3
      run: curl "http://localhost:4566/registry-c3pm-io" -X PUT
    - name: npm install and test
      working-directory: ./back
      run: |
        npm ci
        npm test
      env:
        CI: true
        NODE_ENV: development
        ALLOWED_ORIGIN: http://localhost:3000
        SESSION_SECRET: secret
        REGISTRY_BUCKET_NAME: registry-c3pm-io
        REGISTRY_SECRET: SECRET
        REGISTRY_KEY: KEY
        REGISTRY_URL: http://localhost:4566

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and lint
      working-directory: ./back
      run: |
        npm ci
        npm run lint
      env:
        CI: true
