name: Platform CI

on: [push]

jobs:
  Test :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Launch docker compose
        working-directory: ./
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d
      - name: Install docker test E2E
        working-directory: ./e2e
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
        env:
          CI: true