name: Platform CI

on:
  pull_request:
    paths:
      - '**/**'
      - .github/workflows/platform.yml

jobs:
  Test :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Launch docker compose
      working-directory: ./
      run: |
        docker-compose -f docker-compose.prod.yml up --build -d
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      working-directory: ./e2e
      run : |
        npm ci
        npm test
      env:
        CI: true
