name: Platform CI

on:
  pull_request:
    paths:
      - './'
      - './e2e'
      - .github/workflows/platform.yml

jobs:
  Test :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Launch docker compose
      working-directory: ./
      run: |
        docker-compose -f docker-compose.prod.yml up -d
    - name: Install dependencies and test E2E
      working-directory: ./e2e
      run: |
        docker run -p 4569:4569 -d --name s3 gliffy/fake-s3
        curl "http://localhost:4569/c3pm-registry-io" -X PUT
        npm ci
        npm run cypress
      env:
        CI: true
